language: cpp
os: linux
jobs:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: ROOT_URL="https://root.cern/download/root_v6.18.04.Linux-ubuntu14-x86_64-gcc4.8.tar.gz"
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env: ROOT_URL="https://root.cern/download/root_v6.18.04.macosx64-10.14-clang100.tar.gz"
addons:
  apt:
    packages: 
      - lcov
      - libx11-dev
      - libxpm-dev
      - libxft-dev
      - libxext-dev
  homebrew:
    packages: 
      - lcov
      - coreutils
      - libomp
    update: true

install:
  - cd ../
  - mkdir root
  - travis_retry wget --no-check-certificate --quiet -O - "${ROOT_URL}" | tar --strip-components=1 -xz -C root
  - source root/bin/thisroot.sh
  - . GooStats/setup/download.sh
  - . compile.sh
  - source setup.sh
  - pushd build_GooStats; ln -s ../GooStats/setup/upload.sh; popd

script:
  - pushd GooStats/Modules/naive-Reactor; export COVERAGE=1; make test; popd
  - cd build_GooStats; ctest --output-on-failure

after_success:
  - ./upload.sh
